[package]
name = "blueshift_vault"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
pinocchio = "0.9.2"
pinocchio-system = "0.4.0"

[dev-dependencies]
litesvm = "0.8.2"
solana-sdk = "3.0.0"
